name: Build Branch SNAPSHOT

# run this workflow when build.yml succedes https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
on:
  workflow_run:
      workflows: [Build and Test]
      types:
      - completed  
  workflow_dispatch:
  # push:
  #   branches:
  #     - '**DAT-**'
env:
  MAVEN_VERSION: '3.9.2'
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'    

  build:
    name: Build & Package
    runs-on: ubuntu-22.04
    needs: [setup]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java for publishing to GitHub Repository
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          server-id: github
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: ${{ env.MAVEN_VERSION }}

      # Version artifact based off of branch and commit SHA.
      - name: Version Artifact
        run: mvn versions:set -DnewVersion="${{ github.ref_name }}-SNAPSHOT" 


      # This would still deploy a package if there are test failures. Might help to have build.yml complete and then run this workflow
      # Publish to GitHub Packages. We are building a tar file which includes liquibase-commercial hence we need -Dliquibase-pro.version
      - name: Publish package
        run: |
          # Read the value of liquibase-pro.version from build.yml
          proBranchName=${{ needs.setup.outputs.proBranchName }}
          mvn -B -P liquibase-commercial clean deploy -DskipTests=true -Dliquibase-pro.version=$proBranchName
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
